### ISSUE TITLE
prepareData() in VideoItemLoader

### ISSUE THREAD

**Issue by IgorGanapolsky** [corochann/AndroidTVappTutorial#2]
Hi,
thanks for your nice example repo.  I want to know - why you have a method `prepareData()` in your VideoItemLoader, and never call it.  You described it in your blog post: http://corochann.com/background-data-loading-android-tv-application-hands-on-tutorial-15-535.html#comment-1919.  

However, in your code, you are actually calling `VideoProvider.buildMedia()`.  Please advise.

Igor

**Comment by corochann** [comment]
Hi @IgorGanapolsky ,
Oh you are chacking in detail. 

Actually, `prepareData()` method was used until chapter 15. It is hard-coded data preparation for easy data preparation. The code until this chapter, which uses `prepareData()` can be found in this [this commit](https://github.com/corochann/AndroidTVappTutorial/tree/2ace6518b8c67636d2ed50ca9541ce4480d23ee7).

And I'm now writing chapter 16 to prepare video data from the internet to dynamically change video data shown on app. This is what `VideoProvider.buildMedia()` method is doing. I will update blog soon! sorry for the slow update recently.
