### ISSUE TITLE
IconHeaderItemPresenter haven't focus after update support libs

### ISSUE THREAD

**Issue by wrozwad** [corochann/AndroidTVappTutorial#3]
After updating support libs from 23.4.0 to 24.0.0 left sidebar in `BrowseFragment` stopped worked. In Google sample - androidtv-Leanback they fixed it by adding below two lines of code. Yea, I'm a little too lazy to create pull request so - can you add this to lines to [IconHeaderItemPresenter](https://github.com/corochann/AndroidTVappTutorial/blob/028a6b0d4608b88c7d3df51c6b047be2ef6834a7/app/src/main/java/com/corochann/androidtvapptutorial/ui/presenter/IconHeaderItemPresenter.java):34? :wink:

```java
@Override
public ViewHolder onCreateViewHolder(ViewGroup viewGroup) {
    ...
    view.setFocusable(true);
    view.setAlpha(unselectedAlpha); // Initialize icons to be at half-opacity.

    return new ViewHolder(view);
}
```

**Comment by corochann** [comment]
Thank you for the comment, I appreciate. Could you send me pull request?
